spring.application.name=security-data

# === Configuração do Banco Principal (PostgreSQL) ===
spring.datasource.primary.jdbc-url=jdbc:postgresql://ep-broad-voice-aqrsi449.c-8.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.primary.username=neondb_owner
spring.datasource.primary.password=npg_9v1gjErpCMnB
spring.datasource.primary.driver-class-name=org.postgresql.Driver

# === Configuração do Banco Secundário (H2 Local) ===
spring.datasource.secondary.jdbc-url=jdbc:h2:file:./data/security_data_db
spring.datasource.secondary.username=sa
spring.datasource.secondary.password=
spring.datasource.secondary.driver-class-name=org.h2.Driver

# Configuração do H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurações Globais do JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#-------- IMPORTANTE ------#
#email:ker.a.sm.ia.8.4@gmail.com
#senha:Biro123@
#